/* Generated by AN DISI Unibo */ 
package it.unibo.wis

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Wis ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
				var distance=999
				var weight=0
				var robot=""
				var incinerator="off"
				var robot_sent=0
				var ash_available=0
				var DLIMIT=300
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name		START")
						delay(1000) 
						subscribeToLocalActor("incinerator") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
				state("ready") { //this:State
					action { //it:State
						CommUtils.outgreen("$name		READY")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t127",targetState="handle_activation",cond=whenDispatch("activation_command"))
					transition(edgeName="t128",targetState="handle_sonar",cond=whenDispatch("sonar_value"))
					transition(edgeName="t129",targetState="handle_weight",cond=whenDispatch("weight"))
					transition(edgeName="t130",targetState="handle_robot_init",cond=whenDispatch("work"))
				}	 
				state("handle_sonar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonar_value(K)"), Term.createTerm("sonar_value(K)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 distance=payloadArg(0).toInt()  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitchGuarded({ incinerator=="off"  
					}) )
					transition( edgeName="goto",targetState="activated", cond=doswitchGuarded({! ( incinerator=="off"  
					) }) )
				}	 
				state("handle_weight") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("weight(N)"), Term.createTerm("weight(K)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 weight=payloadArg(0).toInt()  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitchGuarded({ incinerator=="off"  
					}) )
					transition( edgeName="goto",targetState="activated", cond=doswitchGuarded({! ( incinerator=="off"  
					) }) )
				}	 
				state("handle_robot_init") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("work(X)"), Term.createTerm("work(K)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 robot=payloadArg(0)  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitchGuarded({ incinerator=="off"  
					}) )
					transition( edgeName="goto",targetState="activated", cond=doswitchGuarded({! ( incinerator=="off"  
					) }) )
				}	 
				state("handle_activation") { //this:State
					action { //it:State
						 incinerator="on"  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="activated", cond=doswitch() )
				}	 
				state("activated") { //this:State
					action { //it:State
						CommUtils.outgreen("$name	INFO:	weight: $weight	distance: $distance	incinerator: $incinerator		robot: $robot	ash: $ash_available")
						if(  weight>7 && distance>DLIMIT && incinerator!="burning" && (robot=="waiting_home" || robot=="job_done") && robot_sent==0 && ash_available==0  
						 ){forward("take_RP", "take_RP(X)" ,"op_robot" ) 
						 robot_sent=1  
						}
						if(  distance>DLIMIT && incinerator=="on" && (robot=="waiting_home" || robot=="job_done") && robot_sent==0 && ash_available==1  
						 ){forward("take_ash", "take_ash(X)" ,"op_robot" ) 
						 robot_sent=1  
						}
						if(  ((robot=="job_done" && weight<=7) || (robot=="job_done" && distance<=DLIMIT) || (robot=="job_done" && incinerator=="burning")) && robot_sent==0  
						 ){forward("go_home", "go_home(X)" ,"op_robot" ) 
						 robot_sent=1  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t131",targetState="handle_sonar",cond=whenDispatch("sonar_value"))
					transition(edgeName="t132",targetState="handle_weight",cond=whenDispatch("weight"))
					transition(edgeName="t133",targetState="handle_ash",cond=whenEvent("burn_end"))
					transition(edgeName="t134",targetState="handle_work",cond=whenDispatch("work"))
				}	 
				state("handle_work") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("work(X)"), Term.createTerm("work(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 robot=payloadArg(0)  
								CommUtils.outgreen("$name	ROBOT_STATE:	$robot")
						}
						 robot_sent=0  
						if(  robot=="waste_in_incinerator"  
						 ){ incinerator="burning"  
						forward("burn_start", "burn_start(0)" ,"incinerator" ) 
						forward("burn_start", "burn_start(0)" ,"monitoring_device" ) 
						}
						if(  robot=="ash_taken"  
						 ){ ash_available=0  
						forward("ash_taken", "ash_taken(0)" ,"incinerator" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="activated", cond=doswitch() )
				}	 
				state("handle_ash") { //this:State
					action { //it:State
						 
									ash_available=1 
									incinerator="on" 
						CommUtils.outgreen("$name	BURNEND LETTO")
						forward("burn_end", "burn_end(0)" ,"monitoring_device" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="activated", cond=doswitch() )
				}	 
				state("retrieve_ash") { //this:State
					action { //it:State
						CommUtils.outgreen("$name		robot will retrieve ash")
						forward("take_ash", "take_ash(X)" ,"op_robot" ) 
						delay(15000) 
						forward("ash_taken", "ash_taken(N)" ,"incinerator" ) 
						forward("go_home", "go_home(X)" ,"op_robot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
