/* Generated by AN DISI Unibo */ 
package it.unibo.test_observer

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Test_observer ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 
				var A : String = "" 
				var Comulative : String = "" 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						observeResource("localhost","8080","ctxwis","wis_mock","work")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t057",targetState="handle_request",cond=whenRequest("test_request"))
				}	 
				state("handle_request") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t058",targetState="send_data",cond=whenDispatch("work"))
				}	 
				state("send_data") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("work(X)"), Term.createTerm("work(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												A = payloadArg(0) 
												Comulative +=  A + ","
								if(  A=="job_done"  
								 ){ Comulative = "'"+ Comulative + "'"  
								CommUtils.outred("ending.......")
								answer("test_request", "test_reply", "test_reply($Comulative)"   )  
								 System.exit(0)  
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t059",targetState="send_data",cond=whenDispatch("work"))
				}	 
			}
		}
} 
