/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Led ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 
				lateinit var process : Process
				lateinit var out : java.io.BufferedReader
				var blink = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("START led")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleOn",cond=whenDispatch("led_on"))
					transition(edgeName="t01",targetState="handleOff",cond=whenDispatch("led_off"))
					transition(edgeName="t02",targetState="handleFlashing",cond=whenDispatch("led_flashing"))
				}	 
				state("handleOn") { //this:State
					action { //it:State
						if(  blink == true  
						 ){
										blink = false
										process.destroy()
						}
						CommUtils.outmagenta("LED ON")
						 
									process = Runtime.getRuntime().exec("python led_on.py")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="handleOn",cond=whenDispatch("led_on"))
					transition(edgeName="t04",targetState="handleOff",cond=whenDispatch("led_off"))
					transition(edgeName="t05",targetState="handleFlashing",cond=whenDispatch("led_flashing"))
				}	 
				state("handleOff") { //this:State
					action { //it:State
						if(  blink == true  
						 ){
										blink = false
										process.destroy()
						}
						CommUtils.outmagenta("LED OFF")
						 
									process = Runtime.getRuntime().exec("python led_off.py")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="handleOn",cond=whenDispatch("led_on"))
					transition(edgeName="t07",targetState="handleOff",cond=whenDispatch("led_off"))
					transition(edgeName="t08",targetState="handleFlashing",cond=whenDispatch("led_flashing"))
				}	 
				state("handleFlashing") { //this:State
					action { //it:State
						CommUtils.outmagenta("LED FLASHING")
						if(  blink == false  
						 ){ 
										process = Runtime.getRuntime().exec("python led_blink.py")
										blink = true
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="handleOn",cond=whenDispatch("led_on"))
					transition(edgeName="t010",targetState="handleOff",cond=whenDispatch("led_off"))
					transition(edgeName="t011",targetState="handleFlashing",cond=whenDispatch("led_flashing"))
				}	 
			}
		}
} 
