/* Generated by AN DISI Unibo */ 
package it.unibo.external_agent_ws

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class External_agent_ws ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var KG:Float  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("$name		START")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t113",targetState="send_kg",cond=whenDispatch("kg"))
				}	 
				state("send_kg") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("kg(N)"), Term.createTerm("kg(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 KG = payloadArg(0).toFloat()  
								forward("kg", "kg($KG)" ,"waste_storage" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t114",targetState="send_kg",cond=whenDispatch("kg"))
				}	 
			}
		}
} 
