/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Led ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("START led")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t039",targetState="handleOn",cond=whenDispatch("led_on"))
					transition(edgeName="t040",targetState="handleOff",cond=whenDispatch("led_off"))
					transition(edgeName="t041",targetState="handleFlashing",cond=whenDispatch("led_flashing"))
				}	 
				state("handleOn") { //this:State
					action { //it:State
						CommUtils.outmagenta("LED ON")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t042",targetState="handleOn",cond=whenDispatch("led_on"))
					transition(edgeName="t043",targetState="handleOff",cond=whenDispatch("led_off"))
					transition(edgeName="t044",targetState="handleFlashing",cond=whenDispatch("led_flashing"))
				}	 
				state("handleOff") { //this:State
					action { //it:State
						CommUtils.outmagenta("LED OFF")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t045",targetState="handleOn",cond=whenDispatch("led_on"))
					transition(edgeName="t046",targetState="handleOff",cond=whenDispatch("led_off"))
					transition(edgeName="t047",targetState="handleFlashing",cond=whenDispatch("led_flashing"))
				}	 
				state("handleFlashing") { //this:State
					action { //it:State
						CommUtils.outmagenta("LED FLASHING")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t048",targetState="handleOn",cond=whenDispatch("led_on"))
					transition(edgeName="t049",targetState="handleOff",cond=whenDispatch("led_off"))
					transition(edgeName="t050",targetState="handleFlashing",cond=whenDispatch("led_flashing"))
				}	 
			}
		}
} 
