/* Generated by AN DISI Unibo */ 
package it.unibo.waste_storage

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Waste_storage ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var RP:Int = 0  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("$name	START")
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t120",targetState="convert_kg",cond=whenDispatch("kg"))
				}	 
				state("convert_kg") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("kg(N)"), Term.createTerm("kg(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												var KG = payloadArg(0).toFloat()
												RP += kotlin.math.round(KG/50).toInt()
								CommUtils.outyellow("$name	$KG Kg ===> $RP RP")
								forward("rp_number", "rp_number($RP)" ,"wis_mock" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t121",targetState="convert_kg",cond=whenDispatch("kg"))
				}	 
			}
		}
} 
